/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as TotaalRouteImport } from './routes/totaal'
import { Route as CountCategoryRouteImport } from './routes/count.$category'
import { Route as HistorySnapshotIdRouteImport } from './routes/history.$snapshotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TotaalRoute = TotaalRouteImport.update({
  id: '/totaal',
  path: '/totaal',
  getParentRoute: () => rootRouteImport,
} as any)
const CountCategoryRoute = CountCategoryRouteImport.update({
  id: '/count/$category',
  path: '/count/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySnapshotIdRoute = HistorySnapshotIdRouteImport.update({
  id: '/$snapshotId',
  path: '/$snapshotId',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/totaal': typeof TotaalRoute
  '/count/$category': typeof CountCategoryRoute
  '/history/$snapshotId': typeof HistorySnapshotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/totaal': typeof TotaalRoute
  '/count/$category': typeof CountCategoryRoute
  '/history/$snapshotId': typeof HistorySnapshotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/totaal': typeof TotaalRoute
  '/count/$category': typeof CountCategoryRoute
  '/history/$snapshotId': typeof HistorySnapshotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/history' | '/totaal' | '/count/$category' | '/history/$snapshotId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/totaal' | '/count/$category' | '/history/$snapshotId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/totaal'
    | '/count/$category'
    | '/history/$snapshotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  TotaalRoute: typeof TotaalRoute
  CountCategoryRoute: typeof CountCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totaal': {
      id: '/totaal'
      path: '/totaal'
      fullPath: '/totaal'
      preLoaderRoute: typeof TotaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count/$category': {
      id: '/count/$category'
      path: '/count/$category'
      fullPath: '/count/$category'
      preLoaderRoute: typeof CountCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$snapshotId': {
      id: '/history/$snapshotId'
      path: '/$snapshotId'
      fullPath: '/history/$snapshotId'
      preLoaderRoute: typeof HistorySnapshotIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistorySnapshotIdRoute: typeof HistorySnapshotIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistorySnapshotIdRoute: HistorySnapshotIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRouteWithChildren,
  TotaalRoute: TotaalRoute,
  CountCategoryRoute: CountCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
