INSERT INTO public.items (category, name, unit, sort_order, pack_size, units_per_pack) VALUES
('conway_snacks','DORITOS BITS TWIST.H.BBQ 30G.','LOS',1,NULL,NULL),
('conway_snacks','DORITOS BITS TWIST.H.BBQ 30G.','DOOS',2,'30 st./doos',30),
('conway_snacks','DORITOS BITS SWEET PAPR.33G.','LOS',3,NULL,NULL),
('conway_snacks','DORITOS BITS SWEET PAPR.33G.','DOOS',4,'30 st./doos',30),
('conway_snacks','DORITOS WHOPPER TORITILLA 170G','LOS',5,NULL,NULL),
('conway_snacks','DORITOS WHOPPER TORITILLA 170G','DOOS',6,'10 st./doos',10),
('conway_snacks','CROKY CHIPS NATUREL 150G','LOS',7,NULL,NULL),
('conway_snacks','CROKY CHIPS NATUREL 150G','DOOS',8,'20 st./doos',20),
('conway_snacks','CROKY CHIPS PAPRIKA 150G','LOS',9,NULL,NULL),
('conway_snacks','CROKY CHIPS PAPRIKA 150G','DOOS',10,'20 st./doos',20),
('conway_snacks','CROKY CHIPS BOLOGNESE 150G','LOS',11,NULL,NULL),
('conway_snacks','CROKY CHIPS BOLOGNESE 150G','DOOS',12,'20 st./doos',20),
('conway_snacks','CROKY CHIPS PICKLES 150G','LOS',13,NULL,NULL),
('conway_snacks','CROKY CHIPS PICKLES 150G','DOOS',14,'20 st./doos',20),
('conway_snacks','CROKY CHIPS BICKY 150G','LOS',15,NULL,NULL),
('conway_snacks','CROKY CHIPS BICKY 150G','DOOS',16,'20 st./doos',20),
('conway_snacks','CROKY CHIPS KETCHUP 150G','LOS',17,NULL,NULL),
('conway_snacks','CROKY CHIPS KETCHUP 150G','DOOS',18,'20 st./doos',20),
('conway_snacks','CROKY EXPLOS. THAI CURRY 150G','LOS',19,NULL,NULL),
('conway_snacks','CROKY EXPLOS. THAI CURRY 150G','DOOS',20,'9 st./doos',9),
('conway_snacks','CROKY EXPLOS. PIZZA PEPP. 150G','LOS',21,NULL,NULL),
('conway_snacks','CROKY EXPLOS. PIZZA PEPP. 150G','DOOS',22,'9 st./doos',9),
('conway_snacks','CROKY EXPLOS. SWEET CHILI 150G','LOS',23,NULL,NULL),
('conway_snacks','CROKY EXPLOS. SWEET CHILI 150G','DOOS',24,'9 st./doos',9),
('conway_snacks','CROKY EXPLOS. SALT & PEPER 150G','LOS',25,NULL,NULL),
('conway_snacks','CROKY EXPLOS. SALT & PEPER 150G','DOOS',26,'9 st./doos',9),
('conway_snacks','CROKY RINGS PAPRIKA 75G','LOS',27,NULL,NULL),
('conway_snacks','CROKY RINGS PAPRIKA 75G','DOOS',28,'24 st./doos',24),
('conway_snacks','CROKY RINGS BOLOGNESE 75G','LOS',29,NULL,NULL),
('conway_snacks','CROKY RINGS BOLOGNESE 75G','DOOS',30,'24 st./doos',24),
('conway_snacks','CROKY RINGS BBQ 75G','LOS',31,NULL,NULL),
('conway_snacks','CROKY RINGS BBQ 75G','DOOS',32,'24 st./doos',24),
('conway_snacks','CROKY RIBBLE ROCK PAPR. 130G','LOS',33,NULL,NULL),
('conway_snacks','CROKY RIBBLE ROCK PAPR. 130G','DOOS',34,'9 st./doos',9),
('conway_snacks','CROKY ROLLERS SMOKEY BBQ 100G','LOS',35,NULL,NULL),
('conway_snacks','CROKY ROLLERS SMOKEY BBQ 100G','DOOS',36,'9 st./doos',9),
('conway_snacks','CROKY TUBES NACHO CHEESE 100G','LOS',37,NULL,NULL),
('conway_snacks','CROKY TUBES NACHO CHEESE 100G','DOOS',38,'12 st./doos',12),
('conway_snacks','CROKY TUBES SWEET CHILI 100G','LOS',39,NULL,NULL),
('conway_snacks','CROKY TUBES SWEET CHILI 100G','DOOS',40,'12 st./doos',12),
('conway_snacks','CROKY PATATAS FR. KETCHUP 100G','LOS',41,NULL,NULL),
('conway_snacks','CROKY PATATAS FR. KETCHUP 100G','DOOS',42,'9 st./doos',9),
('conway_snacks','CROKY PATATAS FR. PICKLES 100G','LOS',43,NULL,NULL),
('conway_snacks','CROKY PATATAS FR. PICKLES 100G','DOOS',44,'9 st./doos',9),
('conway_snacks','CROKY TORTILLA BOLOGNESE 160G','LOS',45,NULL,NULL),
('conway_snacks','CROKY TORTILLA BOLOGNESE 160G','DOOS',46,'10 st./doos',10),
('conway_snacks','CROKY TORTILLA NACHO CHEESE 160G','LOS',47,NULL,NULL),
('conway_snacks','CROKY TORTILLA NACHO CHEESE 160G','DOOS',48,'10 st./doos',10),
('conway_snacks','CROKY TORTILLA PAPRIKA 160G','LOS',49,NULL,NULL),
('conway_snacks','CROKY TORTILLA PAPRIKA 160G','DOOS',50,'10 st./doos',10),
('conway_snacks','LORENZ MONSTER MUNCH ORIG. 75G','LOS',51,NULL,NULL),
('conway_snacks','LORENZ MONSTER MUNCH ORIG. 75G','DOOS',52,'25 st./doos',25),
('conway_snacks','BOUNTY TRIO 85G.','LOS',53,NULL,NULL),
('conway_snacks','BOUNTY TRIO 85G.','DOOS',54,'24 st./doos',24),
('conway_snacks','M&M''S CHOCO TREATBAG 90G','LOS',55,NULL,NULL),
('conway_snacks','M&M''S CHOCO TREATBAG 90G','DOOS',56,'20 st./doos',20),
('conway_snacks','M&M''S CHOCO POUCH 200G','LOS',57,NULL,NULL),
('conway_snacks','M&M''S CHOCO POUCH 200G','DOOS',58,'30 st./doos',30),
('conway_snacks','M&M''S MINI CHOCOLADE 176G','LOS',59,NULL,NULL),
('conway_snacks','M&M''S MINI CHOCOLADE 176G','DOOS',60,'11 st./doos',11),
('conway_snacks','M&M CRISPY 77G','LOS',61,NULL,NULL),
('conway_snacks','M&M CRISPY 77G','DOOS',62,'16 st./doos',16),
('conway_snacks','M&M''S CRISPY POUCH 170G','LOS',63,NULL,NULL),
('conway_snacks','M&M''S CRISPY POUCH 170G','DOOS',64,'27 st./doos',27),
('conway_snacks','M&M''S CRISPY POUCH 374G','LOS',65,NULL,NULL),
('conway_snacks','M&M''S CRISPY POUCH 374G','DOOS',66,'18 st./doos',18),
('conway_snacks','M&M''S CRISPY POUCH 187G','LOS',67,NULL,NULL),
('conway_snacks','M&M''S CRISPY POUCH 187G','DOOS',68,'30 st./doos',30),
('conway_snacks','M&M''S PEANUTS 82G.','LOS',69,NULL,NULL),
('conway_snacks','M&M''S PEANUTS 82G.','DOOS',70,'16 st./doos',16),
('conway_snacks','M&M''S PEANUTS POUCH 200G','LOS',71,NULL,NULL),
('conway_snacks','M&M''S PEANUTS POUCH 200G','DOOS',72,'30 st./doos',30),
('conway_snacks','M&M BROWNIE 176G','LOS',73,NULL,NULL),
('conway_snacks','M&M BROWNIE 176G','DOOS',74,'27 st./doos',27),
('conway_snacks','M&M''S COUCKIE DOUCH 176G','LOS',75,NULL,NULL),
('conway_snacks','M&M''S COUCKIE DOUCH 176G','DOOS',76,'30 st./doos',30),
('conway_snacks','MALTESERS 68G','LOS',77,NULL,NULL),
('conway_snacks','MALTESERS 68G','DOOS',78,'24 st./doos',24),
('conway_snacks','MALTESERS 102GR','LOS',79,NULL,NULL),
('conway_snacks','MALTESERS 102GR','DOOS',80,'22 st./doos',22),
('conway_snacks','MALTESERS POUCH 175G','LOS',81,NULL,NULL),
('conway_snacks','MALTESERS POUCH 175G','DOOS',82,'20 st./doos',20),
('conway_snacks','MARS 2PACK 70G.','LOS',83,NULL,NULL),
('conway_snacks','MARS 2PACK 70G.','DOOS',84,'24 st./doos',24),
('conway_snacks','SNICKERS BIG 2PACK 80GR','LOS',85,NULL,NULL),
('conway_snacks','SNICKERS BIG 2PACK 80GR','DOOS',86,'24 st./doos',24),
('conway_snacks','TWIX XTRA 75G.','LOS',87,NULL,NULL),
('conway_snacks','TWIX XTRA 75G.','DOOS',88,'30 st./doos',30),
('conway_snacks','TWIX WHITE XTRA 75G','LOS',89,NULL,NULL),
('conway_snacks','TWIX WHITE XTRA 75G','DOOS',90,'30 st./doos',30),
('conway_snacks','KINDER BUENO 43G.','LOS',91,NULL,NULL),
('conway_snacks','KINDER BUENO 43G.','DOOS',92,'30 st./doos',30),
('conway_snacks','KINDER BUENO WHITE 39G','LOS',93,NULL,NULL),
('conway_snacks','KINDER BUENO WHITE 39G','DOOS',94,'30 st./doos',30),
('conway_snacks','BELGIANS SUIKERSPIN STRAWB. 35G','LOS',95,NULL,NULL),
('conway_snacks','BELGIANS SUIKERSPIN STRAWB. 35G','DOOS',96,'8 st./doos',8),
('conway_snacks','BELGIANS SUIKERSPIN FRAMB. 35G','LOS',97,NULL,NULL),
('conway_snacks','BELGIANS SUIKERSPIN FRAMB. 35G','DOOS',98,'8 st./doos',8),
('conway_snacks','BELGIANS SUIKERSPIN APPEL 35G','LOS',99,NULL,NULL),
('conway_snacks','BELGIANS SUIKERSPIN APPEL 35G','DOOS',100,'8 st./doos',8),
('conway_snacks','BELGIANS SUIKERSPIN GUM 35G','LOS',101,NULL,NULL),
('conway_snacks','BELGIANS SUIKERSPIN GUM 35G','DOOS',102,'8 st./doos',8),
('conway_snacks','BELGIANS SUIKERSPIN VIOLET 35G','LOS',103,NULL,NULL),
('conway_snacks','BELGIANS SUIKERSPIN VIOLET 35G','DOOS',104,'8 st./doos',8),
('conway_snacks','BELGIANS SUIKERSPIN SNOEPAPP. 35G','LOS',105,NULL,NULL),
('conway_snacks','BELGIANS SUIKERSPIN SNOEPAPP. 35G','DOOS',106,'8 st./doos',8),
('conway_snacks','MENTOS  FRUIT 37,5G.','LOS',107,NULL,NULL),
('conway_snacks','MENTOS  FRUIT 37,5G.','DOOS',108,'40 st./doos',40),
('conway_snacks','MENTOS  MINT 37,5G.','LOS',109,NULL,NULL),
('conway_snacks','MENTOS  MINT 37,5G.','DOOS',110,'40 st./doos',40),
('conway_snacks','MENTOS RAINBOW 37,5G','LOS',111,NULL,NULL),
('conway_snacks','MENTOS RAINBOW 37,5G','DOOS',112,'40 st./doos',40),
('conway_snacks','CRAC A NUT PAPR. NOOTJES 200G','LOS',113,NULL,NULL),
('conway_snacks','CRAC A NUT PAPR. NOOTJES 200G','DOOS',114,'21 st./doos',21),
('conway_snacks','DUYVIS CRAC A NUT PAPR. 45G','LOS',115,NULL,NULL),
('conway_snacks','DUYVIS CRAC A NUT PAPR. 45G','DOOS',116,'20 st./doos',20),
('conway_snacks','FERRERO NUTELLA & co 52G','LOS',117,NULL,NULL),
('conway_snacks','FERRERO NUTELLA & co 52G','DOOS',118,'12 st./doos',12),
('conway_snacks','B&J.CHOCOL.FUDGE BROWNIE 100ML','LOS',119,NULL,NULL),
('conway_snacks','B&J.CHOCOL.FUDGE BROWNIE 100ML','DOOS',120,'12 st./doos',12),
('conway_snacks','B&J.COOKIE DOUGH 100ML.','LOS',121,NULL,NULL),
('conway_snacks','B&J.COOKIE DOUGH 100ML.','DOOS',122,'12 st./doos',12),
('conway_snacks','CALIPPO COLA 105ML','LOS',123,NULL,NULL),
('conway_snacks','CALIPPO COLA 105ML','DOOS',124,'24 st./doos',24),
('conway_snacks','CALIPPO ORANGE 105ML','LOS',125,NULL,NULL),
('conway_snacks','CALIPPO ORANGE 105ML','DOOS',126,'24 st./doos',24),
('conway_snacks','CORNETTO CLASSICO 125ML','LOS',127,NULL,NULL),
('conway_snacks','CORNETTO CLASSICO 125ML','DOOS',128,'24 st./doos',24),
('conway_snacks','OLA CORNETTO STRACC. 140ML','LOS',129,NULL,NULL),
('conway_snacks','OLA CORNETTO STRACC. 140ML','DOOS',130,'24 st./doos',24),
('conway_snacks','CORNETTO KING CONE 260ML VANILE','LOS',131,NULL,NULL),
('conway_snacks','CORNETTO KING CONE 260ML VANILE','DOOS',132,'16 st./doos',16),
('conway_snacks','CORNETTO KING CONE 260ML CHOC.','LOS',133,NULL,NULL),
('conway_snacks','CORNETTO KING CONE 260ML CHOC.','DOOS',134,'16 st./doos',16),
('conway_snacks','MAGNUM BOMBONIERA 6 PRAL.72ML','LOS',135,NULL,NULL),
('conway_snacks','MAGNUM BOMBONIERA 6 PRAL.72ML','DOOS',136,'28 st./doos',28),
('conway_snacks','MAGNUM ALMOND 110ML','LOS',137,NULL,NULL),
('conway_snacks','MAGNUM ALMOND 110ML','DOOS',138,'20 st./doos',20),
('conway_snacks','MAGNUM CLASSIC 110ML','LOS',139,NULL,NULL),
('conway_snacks','MAGNUM CLASSIC 110ML','DOOS',140,'20 st./doos',20),
('conway_snacks','MAGNUM AARDBEI/WHITE 100ML','LOS',141,NULL,NULL),
('conway_snacks','MAGNUM AARDBEI/WHITE 100ML','DOOS',142,'20 st./doos',20),
('conway_snacks','MAGNUM WHITE 110ML','LOS',143,NULL,NULL),
('conway_snacks','MAGNUM WHITE 110ML','DOOS',144,'20 st./doos',20),
('conway_snacks','MAGNUM DOUBLE CHOCOLAT 85ML','LOS',145,NULL,NULL),
('conway_snacks','MAGNUM DOUBLE CHOCOLAT 85ML','DOOS',146,'20 st./doos',20),
('conway_snacks','MAGNUM IJSSTICK EUPHORIA 90ML','LOS',147,NULL,NULL),
('conway_snacks','MAGNUM IJSSTICK EUPHORIA 90ML','DOOS',148,'20 st./doos',20),
('conway_snacks','MAGNUM DBL GLD CARM BILL. 85ML','LOS',149,NULL,NULL),
('conway_snacks','MAGNUM DBL GLD CARM BILL. 85ML','DOOS',150,'20 st./doos',20),
('conway_snacks','MAGNUM UTOPIA 85ML','LOS',151,NULL,NULL),
('conway_snacks','MAGNUM UTOPIA 85ML','DOOS',152,'20 st./doos',20),
('conway_snacks','OLA SUPER TWISTER 110ML','LOS',153,NULL,NULL),
('conway_snacks','OLA SUPER TWISTER 110ML','DOOS',154,'28 st./doos',28),
('conway_snacks','BOUNTY ICE BAR X-TRA 51,6G','LOS',155,NULL,NULL),
('conway_snacks','BOUNTY ICE BAR X-TRA 51,6G','DOOS',156,'24 st./doos',24),
('conway_snacks','MARS ICE BAR X-TRA 60G','LOS',157,NULL,NULL),
('conway_snacks','MARS ICE BAR X-TRA 60G','DOOS',158,'24 st./doos',24),
('conway_snacks','SNICKERS ICE BAR X-TRA 66G','LOS',159,NULL,NULL),
('conway_snacks','SNICKERS ICE BAR X-TRA 66G','DOOS',160,'24 st./doos',24),
('conway_snacks','SNICKERS PEANUT BUTTER BAR 53G','LOS',161,NULL,NULL),
('conway_snacks','SNICKERS PEANUT BUTTER BAR 53G','DOOS',162,'24 st./doos',24),
('conway_snacks','SNICKERS WHITE SINGLE BAR 55G','LOS',163,NULL,NULL),
('conway_snacks','SNICKERS WHITE SINGLE BAR 55G','DOOS',164,'24 st./doos',24),
('conway_snacks','TWIX ICE CREAM SINGLE BAR 47G','LOS',165,NULL,NULL),
('conway_snacks','TWIX ICE CREAM SINGLE BAR 47G','DOOS',166,'24 st./doos',24);
