delete from public.counts;
delete from public.items;
insert into public.items (category,name,unit,sort_order) values
('snoeptoog','CROKY CHIPS NATUREL 150G','LOS',1),
('snoeptoog','CROKY CHIPS NATUREL 150G','DOOS',2),
('snoeptoog','CROKY CHIPS PAPRIKA 150G','LOS',3),
('snoeptoog','CROKY CHIPS PAPRIKA 150G','DOOS',4),
('snoeptoog','CROKY TORTILLA PAPRIKA','LOS',5),
('snoeptoog','CROKY TORTILLA PAPRIKA','DOOS',6),
('snoeptoog','CROKY TORTILLA CHEESE','LOS',7),
('snoeptoog','CROKY TORTILLA CHEESE','DOOS',8),
('snoeptoog','CROKY TORTILLA BOLOGNESE','LOS',9),
('snoeptoog','CROKY TORTILLA BOLOGNESE','DOOS',10),
('snoeptoog','CROKY EXPLOS. THAI CURRY 150G','LOS',11),
('snoeptoog','CROKY EXPLOS. THAI CURRY 150G','DOOS',12),
('snoeptoog','CROKY EXPLOS. SWEET CHILI 150G','LOS',13),
('snoeptoog','CROKY EXPLOS. SWEET CHILI 150G','DOOS',14),
('snoeptoog','CROKY EXPLOS. SALT & PEPER 150G','LOS',15),
('snoeptoog','CROKY EXPLOS. SALT & PEPER 150G','DOOS',16),
('snoeptoog','CROKY RINGS PAPRIKA 75G','LOS',17),
('snoeptoog','CROKY RINGS PAPRIKA 75G','DOOS',18),
('snoeptoog','CROKY RINGS BOLOGNESE 75G','LOS',19),
('snoeptoog','CROKY RINGS BOLOGNESE 75G','DOOS',20),
('snoeptoog','CROKY RINGS BBQ 75G','LOS',21),
('snoeptoog','CROKY RINGS BBQ 75G','DOOS',22),
('snoeptoog','CROKY PATATAS FR. KETCHUP 100G','LOS',23),
('snoeptoog','CROKY PATATAS FR. KETCHUP 100G','DOOS',24),
('snoeptoog','CROKY PATATAS FR. PICKLES 100G','LOS',25),
('snoeptoog','CROKY PATATAS FR. PICKLES 100G','DOOS',26),
('snoeptoog','BOUNTY TRIO 85G.','LOS',27),
('snoeptoog','BOUNTY TRIO 85G.','DOOS',28),
('snoeptoog','MARS 75G','LOS',29),
('snoeptoog','MARS 75G','DOOS',30),
('snoeptoog','SNICKERS 75G','LOS',31),
('snoeptoog','SNICKERS 75G','DOOS',32),
('snoeptoog','TWIX 75G','LOS',33),
('snoeptoog','TWIX 75G','DOOS',34),
('snoeptoog','TWIX WHITE 75G','LOS',35),
('snoeptoog','TWIX WHITE 75G','DOOS',36),
('snoeptoog','KINDER BUENO 43G.','LOS',37),
('snoeptoog','KINDER BUENO 43G.','DOOS',38),
('snoeptoog','KINDER BUENO WHITE 43G.','LOS',39),
('snoeptoog','KINDER BUENO WHITE 43G.','DOOS',40),
('snoeptoog','M&M''S CHOCO POUCH 220G','LOS',41),
('snoeptoog','M&M''S CHOCO POUCH 220G','DOOS',42),
('snoeptoog','M&M''S CHOCO TREATBAG 100G','LOS',43),
('snoeptoog','M&M''S CHOCO TREATBAG 100G','DOOS',44),
('snoeptoog','M&M''S CRISPY POUCH 170G','LOS',45),
('snoeptoog','M&M''S CRISPY POUCH 170G','DOOS',46),
('snoeptoog','M&M''S CRISPY TREATBAG 77G','LOS',47),
('snoeptoog','M&M''S CRISPY TREATBAG 77G','DOOS',48),
('snoeptoog','M&M''S PEANUTS POUCH 220G','LOS',49),
('snoeptoog','M&M''S PEANUTS POUCH 220G','DOOS',50),
('snoeptoog','M&M''S PEANUTS 90G.','LOS',51),
('snoeptoog','M&M''S PEANUTS 90G.','DOOS',52),
('snoeptoog','M&M''S PEANUTS MINI POUCH','LOS',53),
('snoeptoog','M&M''S PEANUTS MINI POUCH','DOOS',54),
('snoeptoog','M&M''S SALTED CARAMEL','LOS',55),
('snoeptoog','M&M''S SALTED CARAMEL','DOOS',56),
('snoeptoog','M&M''S COOKIE DOUGH','LOS',57),
('snoeptoog','M&M''S COOKIE DOUGH','DOOS',58),
('snoeptoog','MALTESERS POUCH 175G','LOS',59),
('snoeptoog','MALTESERS POUCH 175G','DOOS',60),
('snoeptoog','MENTOS FRUIT 37,5G.','LOS',61),
('snoeptoog','MENTOS FRUIT 37,5G.','DOOS',62),
('snoeptoog','MENTOS MINT 37,5G.','LOS',63),
('snoeptoog','MENTOS MINT 37,5G.','DOOS',64),
('snoeptoog','MENTOS RAINBOW 37,5G','LOS',65),
('snoeptoog','MENTOS RAINBOW 37,5G','DOOS',66),
('snoeptoog','CRAC A NUT PAPR. NOOTJES 200G','LOS',67),
('snoeptoog','CRAC A NUT PAPR. NOOTJES 200G','DOOS',68),
('snoeptoog','DUYVIS CRAC A NUT PAPR. 45G','LOS',69),
('snoeptoog','DUYVIS CRAC A NUT PAPR. 45G','DOOS',70),
('snoeptoog','FERRERO NUTELLA & co 52G','LOS',71),
('snoeptoog','FERRERO NUTELLA & co 52G','DOOS',72),
('snoeptoog','BELGIANS SUIKERSPIN STRAWB. 35G','LOS',73),
('snoeptoog','BELGIANS SUIKERSPIN STRAWB. 35G','DOOS',74),
('snoeptoog','SUPREME CHEESE SAUS 90GR','LOS',75),
('snoeptoog','SUPREME CHEESE SAUS 90GR','DOOS',76),
('snoeptoog','SUPREME NACHOS BARBECUE 140GR','LOS',77),
('snoeptoog','SUPREME NACHOS BARBECUE 140GR','DOOS',78),
('snoeptoog','SUPREME NACHO SALTED 140GR','LOS',79),
('snoeptoog','SUPREME NACHO SALTED 140GR','DOOS',80),
('snoeptoog','SUPREME SALSA SAUS 90GR','LOS',81),
('snoeptoog','SUPREME SALSA SAUS 90GR','DOOS',82),
('snoeptoog','RAVIER NACHOS FOLDING TRAY REGULAR','LOS',83),
('snoeptoog','RAVIER NACHOS FOLDING TRAY REGULAR','DOOS',84),
('snoeptoog','PATHE BE FOLDINBOX SUCRE 125CL','LOS',85),
('snoeptoog','PATHE BE FOLDINBOX SUCRE 125CL','DOOS',86),
('snoeptoog','PATHE BE FOLDINBOX SUCRE 250CL','LOS',87),
('snoeptoog','PATHE BE FOLDINBOX SUCRE 250CL','DOOS',88),
('snoeptoog','PATHE BE FOLDINBOX SUCRE 500CL','LOS',89),
('snoeptoog','PATHE BE FOLDINBOX SUCRE 500CL','DOOS',90),
('snoeptoog','PATHE BE GOBELET SALE 125CL','LOS',91),
('snoeptoog','PATHE BE GOBELET SALE 125CL','DOOS',92),
('snoeptoog','PATHE BE GOBELET SALE 250CL','LOS',93),
('snoeptoog','PATHE BE GOBELET SALE 250CL','DOOS',94),
('snoeptoog','PATHE BE GOBELET SPECIAL EDITION 500CL','LOS',95),
('snoeptoog','PATHE BE GOBELET SPECIAL EDITION 500CL','DOOS',96),
('snoeptoog','POPCORN ZOUT','DOOS',97),
('snoeptoog','POPCORN ZOET','DOOS',98),
('snoeptoog','POPCORN MIX','DOOS',99),
('ijs_berging','B&J.CHOCOL.FUDGE BROWNIE 100ML','LOS',1),
('ijs_berging','B&J.CHOCOL.FUDGE BROWNIE 100ML','DOOS',2),
('ijs_berging','B&J.COOKIE DOUGH 100ML.','LOS',3),
('ijs_berging','B&J.COOKIE DOUGH 100ML.','DOOS',4),
('ijs_berging','CALIPPO COLA 105ML','LOS',5),
('ijs_berging','CALIPPO COLA 105ML','DOOS',6),
('ijs_berging','CALIPPO ORANGE 105ML','LOS',7),
('ijs_berging','CALIPPO ORANGE 105ML','DOOS',8),
('ijs_berging','CORNETTO CLASSICO 125ML','LOS',9),
('ijs_berging','CORNETTO CLASSICO 125ML','DOOS',10),
('ijs_berging','OLA CORNETTO STRACC. 140ML','LOS',11),
('ijs_berging','OLA CORNETTO STRACC. 140ML','DOOS',12),
('ijs_berging','CORNETTO KING CONE 260ML VANILE','LOS',13),
('ijs_berging','CORNETTO KING CONE 260ML VANILE','DOOS',14),
('ijs_berging','CORNETTO KING CONE 260ML CHOC.','LOS',15),
('ijs_berging','CORNETTO KING CONE 260ML CHOC.','DOOS',16),
('ijs_berging','MAGNUM BOMBONIERA 6 PRAL.72ML','LOS',17),
('ijs_berging','MAGNUM BOMBONIERA 6 PRAL.72ML','DOOS',18),
('ijs_berging','MAGNUM BOMBONIERA 12 PRAL.144ML','LOS',19),
('ijs_berging','MAGNUM BOMBONIERA 12 PRAL.144ML','DOOS',20),
('ijs_berging','MAGNUM BONBON GCB 12ST 204ML','LOS',21),
('ijs_berging','MAGNUM BONBON GCB 12ST 204ML','DOOS',22),
('ijs_berging','MAGNUM BONBON SC 12ST 204ML','LOS',23),
('ijs_berging','MAGNUM BONBON SC 12ST 204ML','DOOS',24),
('ijs_berging','MAGNUM ALMOND 110ML','LOS',25),
('ijs_berging','MAGNUM ALMOND 110ML','DOOS',26),
('ijs_berging','MAGNUM CLASSIC 110ML','LOS',27),
('ijs_berging','MAGNUM CLASSIC 110ML','DOOS',28),
('ijs_berging','MAGNUM AARDBEI/WHITE 100ML','LOS',29),
('ijs_berging','MAGNUM AARDBEI/WHITE 100ML','DOOS',30),
('ijs_berging','MAGNUM WHITE 110ML','LOS',31),
('ijs_berging','MAGNUM WHITE 110ML','DOOS',32),
('ijs_berging','MAGNUM DOUBLE CHOCOLAT 85ML','LOS',33),
('ijs_berging','MAGNUM DOUBLE CHOCOLAT 85ML','DOOS',34),
('ijs_berging','MAGNUM IJSSTICK EUPHORIA 90ML','LOS',35),
('ijs_berging','MAGNUM IJSSTICK EUPHORIA 90ML','DOOS',36),
('ijs_berging','MAGNUM CARAMEL NUTS BAR 85ML','LOS',37),
('ijs_berging','MAGNUM CARAMEL NUTS BAR 85ML','DOOS',38),
('ijs_berging','MAGNUM DBL GLD CARM BILL. 85ML','LOS',39),
('ijs_berging','MAGNUM DBL GLD CARM BILL. 85ML','DOOS',40),
('ijs_berging','MAGNUM DOUBLE STARCHASER 85ML','LOS',41),
('ijs_berging','MAGNUM DOUBLE STARCHASER 85ML','DOOS',42),
('ijs_berging','MAGNUM UTOPIA 85ML','LOS',43),
('ijs_berging','MAGNUM UTOPIA 85ML','DOOS',44),
('ijs_berging','OLA SUPER TWISTER 110ML','LOS',45),
('ijs_berging','OLA SUPER TWISTER 110ML','DOOS',46),
('ijs_berging','BOUNTY ICE BAR X-TRA 51,6G','LOS',47),
('ijs_berging','BOUNTY ICE BAR X-TRA 51,6G','DOOS',48),
('ijs_berging','MARS ICE BAR X-TRA 60G','LOS',49),
('ijs_berging','MARS ICE BAR X-TRA 60G','DOOS',50),
('ijs_berging','SNICKERS ICE BAR X-TRA 66G','LOS',51),
('ijs_berging','SNICKERS ICE BAR X-TRA 66G','DOOS',52),
('ijs_berging','SNICKERS PEANUT BUTTER BAR 53G','LOS',53),
('ijs_berging','SNICKERS PEANUT BUTTER BAR 53G','DOOS',54),
('ijs_berging','SNICKERS WHITE SINGLE BAR 55G','LOS',55),
('ijs_berging','SNICKERS WHITE SINGLE BAR 55G','DOOS',56),
('ijs_berging','TWIX ICE CREAM SINGLE BAR 47G','LOS',57),
('ijs_berging','TWIX ICE CREAM SINGLE BAR 47G','DOOS',58),
('ijs_berging','OUFTI BANAAN','LOS',59),
('ijs_berging','OUFTI BANAAN','DOOS',60),
('ijs_berging','OUFTI AARBEI','LOS',61),
('ijs_berging','OUFTI AARBEI','DOOS',62),
('ijs_berging','OUFTI BANAAN-SPECULOOS','LOS',63),
('ijs_berging','OUFTI BANAAN-SPECULOOS','DOOS',64),
('ijs_berging','OUFTI BANAAN-CARAMEL','LOS',65),
('ijs_berging','OUFTI BANAAN-CARAMEL','DOOS',66),
('frigo_los','AQUARIUS ZERO LEMON','LOS',1),
('frigo_los','AQUARIUS RED PEACH','LOS',2),
('frigo_los','CHAUDF STILL 1LTR','LOS',3),
('frigo_los','CHAUDF STILL 33CL','LOS',4),
('frigo_los','CHAUDF STILL 50CL','LOS',5),
('frigo_los','CHAUDF SPARKLING 50CL','LOS',6),
('frigo_los','CHAUDF FRUITY LEMON 50CL','LOS',7),
('frigo_los','COCA COLA 50 CL PET','LOS',8),
('frigo_los','COCA COLA LIGHT LEMON 50 CL PET','LOS',9),
('frigo_los','COCA COLA ZERO 50CL PET','LOS',10),
('frigo_los','COCA COLA CHERRY 50CL PET','LOS',11),
('frigo_los','FANTA LEMON 50CL PET','LOS',12),
('frigo_los','FANTA ORANGE 50CL PET','LOS',13),
('frigo_los','FANTA EXOTIC','LOS',14),
('frigo_los','FANTA Z. FOR BERRIES','LOS',15),
('frigo_los','FUZE TEA GREEN MANGO 4X40CL','LOS',16),
('frigo_los','FUZE TEA GREEN 40CL','LOS',17),
('frigo_los','FUZE TEA PEACH HIBIS 4X40CL','LOS',18),
('frigo_los','FUZE TEA BL. PEACH 4X40CL','LOS',19),
('frigo_los','LIPTON GREEN 6X50CL','LOS',20),
('frigo_los','LIPTON RTD REG.BRUIS 6X50CL.PET','LOS',21),
('frigo_los','LIPTON GRE CITRUS BRUIS 6X50CL.PET','LOS',22),
('frigo_los','LIPTON RTD PEACH 6X50CL.PET','LOS',23),
('frigo_los','LIPTON PEACH NB 6X50CL','LOS',24),
('frigo_los','LIPTON PEACH ZERO 6X50CL','LOS',25),
('frigo_los','LIPTON RASPBERRY 50CL','LOS',26),
('frigo_los','MINUTE MAID MULTIVITAMINE 4X33CL','LOS',27),
('frigo_los','MINUTE MAID ORANGE 33CL PET','LOS',28),
('frigo_los','SPRITE 50CL','LOS',29),
('frigo_los','MONSTER ENERGY 50CL','LOS',30),
('frigo_los','MONSTER JUICE MANGO LOCO 50CL','LOS',31),
('frigo_los','POWERADE MOUNTAIN B. 50CL','LOS',32),
('frigo_los','NALU ORIGINAL 25CL','LOS',33),
('frigo_los','LEFFE BLOND','LOS',34),
('frigo_los','LEFFE BLOND 0%','LOS',35),
('frigo_los','VEDETTE','LOS',36),
('frigo_los','DUVEL 6,66','LOS',37),
('frigo_los','LIEFMANS 0%','LOS',38),
('frigo_los','APPELSIENTJE (1L Brikken LADIESNIGHT)','LOS',39),
('frigo_los','PROSECCO','LOS',40),
('frigo_los','PROSECCO ROSÉ','LOS',41),
('frigo_trays','AQUARIUS ZERO LEMON','TRAYS',1),
('frigo_trays','AQUARIUS RED PEACH','TRAYS',2),
('frigo_trays','CHAUDF STILL 1LTR','TRAYS',3),
('frigo_trays','CHAUDF STILL 33CL','TRAYS',4),
('frigo_trays','CHAUDF STILL 50CL','TRAYS',5),
('frigo_trays','CHAUDF SPARKLING 50CL','TRAYS',6),
('frigo_trays','CHAUDF FRUITY LEMON 50CL','TRAYS',7),
('frigo_trays','COCA COLA 50 CL PET','TRAYS',8),
('frigo_trays','COCA COLA LIGHT LEMON 50 CL PET','TRAYS',9),
('frigo_trays','COCA COLA ZERO 50CL PET','TRAYS',10),
('frigo_trays','COCA COLA CHERRY 50CL PET','TRAYS',11),
('frigo_trays','FANTA LEMON 50CL PET','TRAYS',12),
('frigo_trays','FANTA ORANGE 50CL PET','TRAYS',13),
('frigo_trays','FANTA EXOTIC','TRAYS',14),
('frigo_trays','FANTA Z. FOR BERRIES','TRAYS',15),
('frigo_trays','FUZE TEA GREEN MANGO 4X40CL','TRAYS',16),
('frigo_trays','FUZE TEA GREEN 40CL','TRAYS',17),
('frigo_trays','FUZE TEA PEACH HIBIS 4X40CL','TRAYS',18),
('frigo_trays','FUZE TEA BL. PEACH 4X40CL','TRAYS',19),
('frigo_trays','LIPTON GREEN 6X50CL','TRAYS',20),
('frigo_trays','LIPTON RTD REG.BRUIS 6X50CL.PET','TRAYS',21),
('frigo_trays','LIPTON GRE CITRUS BRUIS 6X50CL.PET','TRAYS',22),
('frigo_trays','LIPTON RTD PEACH 6X50CL.PET','TRAYS',23),
('frigo_trays','LIPTON PEACH NB 6X50CL','TRAYS',24),
('frigo_trays','LIPTON PEACH ZERO 6X50CL','TRAYS',25),
('frigo_trays','LIPTON RASPBERRY 50CL','TRAYS',26),
('frigo_trays','MINUTE MAID MULTIVITAMINE 4X33CL','TRAYS',27),
('frigo_trays','MINUTE MAID ORANGE 33CL PET','TRAYS',28),
('frigo_trays','SPRITE 50CL','TRAYS',29),
('frigo_trays','MONSTER ENERGY 50CL','TRAYS',30),
('frigo_trays','MONSTER JUICE MANGO LOCO 50CL','TRAYS',31),
('frigo_trays','POWERADE MOUNTAIN B. 50CL','TRAYS',32),
('frigo_trays','NALU ORIGINAL 25CL','TRAYS',33),
('frigo_trays','LEFFE BLOND','LOS',34),
('frigo_trays','LEFFE BLOND 0%','LOS',35),
('frigo_trays','VEDETTE','LOS',36),
('frigo_trays','DUVEL 6,66','LOS',37),
('frigo_trays','LIEFMANS 0%','LOS',38),
('frigo_trays','APPELSIENTJE (1L Brikken LADIESNIGHT)','LOS',39),
('frigo_trays','PROSECCO','LOS',40),
('frigo_trays','PROSECCO ROSÉ','LOS',41),
('haribo','HARIBO AARDBEIEN 3KG','KG',1),
('haribo','HARIBO AARDBEIEN 3KG','BAK',2),
('haribo','HARIBO BRAAMBESSEN 3KG','KG',3),
('haribo','HARIBO BRAAMBESSEN 3KG','BAK',4),
('haribo','HARIBO DRAGIBUS 2KG.','KG',5),
('haribo','HARIBO DRAGIBUS 2KG.','BAK',6),
('haribo','HARIBO DRAGIBUS SOFT 2KG.','KG',7),
('haribo','HARIBO DRAGIBUS SOFT 2KG.','BAK',8),
('haribo','HARIBO HAPPY-COLA 3G.1KG.','KG',9),
('haribo','HARIBO HAPPY-COLA 3G.1KG.','BAK',10),
('haribo','HARIBO CHERRY COLA 3KG','KG',11),
('haribo','HARIBO CHERRY COLA 3KG','BAK',12),
('haribo','HARIBO MINI ZURE COLA 3X1KG','KG',13),
('haribo','HARIBO MINI ZURE COLA 3X1KG','BAK',14),
('haribo','HARIBO HAPPY CHERRIES 3X1KG.','KG',15),
('haribo','HARIBO HAPPY CHERRIES 3X1KG.','BAK',16),
('haribo','HARIBO HAPPY CHERRIES FIZZ 3X1KG','KG',17),
('haribo','HARIBO HAPPY CHERRIES FIZZ 3X1KG','BAK',18),
('haribo','HARIBO SMURFEN 3KG','KG',19),
('haribo','HARIBO SMURFEN 3KG','BAK',20),
('haribo','HARIBO PASTA FRUTTA 3X1KG.','KG',21),
('haribo','HARIBO PASTA FRUTTA 3X1KG.','BAK',22),
('haribo','HARIBO HAPPY PEACHES 3KG.','KG',23),
('haribo','HARIBO HAPPY PEACHES 3KG.','BAK',24),
('haribo','HARIBO ROTELLA FRUIT 1KG.','KG',25),
('haribo','HARIBO ROTELLA FRUIT 1KG.','BAK',26),
('haribo','HARIBO COOL BANANA''S 3KG','BAK',27),
('haribo','LUTTI BUBBLIZZ 2KG','KG',28),
('haribo','LUTTI BUBBLIZZ 2KG','BAK',29),
('haribo','LUTTI DRACULA TANDEN 3KG','KG',30),
('haribo','LUTTI DRACULA TANDEN 3KG','BAK',31),
('haribo','LUTTI ZURE DRACULA TANDEN 3KG','KG',32),
('haribo','LUTTI ZURE DRACULA TANDEN 3KG','BAK',33),
('haribo','HARIBO SCHUIMAARDBEIEN','KG',34),
('haribo','HARIBO SCHUIMAARDBEIEN','BAK',35),
('haribo','HARIBO KIKKERS 7G 1KG','KG',36),
('haribo','HARIBO KIKKERS 7G 1KG','BAK',37),
('haribo','HARIBO LOVE FIZZ 1KG','KG',38),
('haribo','HARIBO LOVE FIZZ 1KG','BAK',39),
('haribo','HARIBO PINBALLS ABSOL.APPL 1KG','KG',40),
('haribo','HARIBO PINBALLS ABSOL.APPL 1KG','BAK',41),
('haribo','HARIBO HARTJES FRAMBOOS','KG',42),
('haribo','HARIBO HARTJES FRAMBOOS','BAK',43),
('haribo','HARIBO KROKODILLEN','KG',44),
('haribo','HARIBO KROKODILLEN','BAK',45),
('haribo','HARIBO BALLA BALLA ROOD PICA','KG',46),
('haribo','HARIBO BALLA BALLA ROOD PICA','BAK',47);