ALTER TABLE public.items ADD COLUMN IF NOT EXISTS units_per_pack NUMERIC;

-- Jimmy's: hoeveel stuks/kg per doos (gebruikt om "1" automatisch te vermenigvuldigen)
UPDATE public.items SET units_per_pack = 45 WHERE category = 'jimmys' AND name = 'SUPREME CHEESE SAUS 90GR';
UPDATE public.items SET units_per_pack = 12 WHERE category = 'jimmys' AND name = 'SUPREME NACHOS BARBECUE 140GR';
UPDATE public.items SET units_per_pack = 12 WHERE category = 'jimmys' AND name = 'SUPREME NACHO SALTED 140GR';
UPDATE public.items SET units_per_pack = 45 WHERE category = 'jimmys' AND name = 'SUPREME SALSA SAUS 90GR';
UPDATE public.items SET units_per_pack = 40 WHERE category = 'jimmys' AND name = 'SUPREME FIESTOS 40G';
UPDATE public.items SET units_per_pack = 250 WHERE category = 'jimmys' AND name = 'RAVIER NACHOS FOLDING TRAY REGULAR';
UPDATE public.items SET units_per_pack = 500 WHERE category = 'jimmys' AND name = 'PATHE BE GOBELET SUCRE 125CL (POPCORN DOOS ZOET)';
UPDATE public.items SET units_per_pack = 250 WHERE category = 'jimmys' AND name = 'PATHE BE GOBELET SUCRE 250CL (POPCORN DOOS ZOET)';
UPDATE public.items SET units_per_pack = 125 WHERE category = 'jimmys' AND name = 'PATHE BE GOBELET SUCRE 500CL (POPCORN DOOS ZOET)';
UPDATE public.items SET units_per_pack = 500 WHERE category = 'jimmys' AND name = 'PATHE BE GOBELET SALE 125CL (POPCORN DOOS ZOUT)';
UPDATE public.items SET units_per_pack = 250 WHERE category = 'jimmys' AND name = 'PATHE BE GOBELET SALE 250CL (POPCORN DOOS ZOUT)';
UPDATE public.items SET units_per_pack = 250 WHERE category = 'jimmys' AND name = 'PATHE BE GOBELET SALE 250CL (POPCORN DOOS ZOET/ZOUT MIX)';
UPDATE public.items SET units_per_pack = 3   WHERE category = 'jimmys' AND name = 'SAC POPCORN AIR POPPED SALTED JIMMY''S (POPCORN ZOUT)';
UPDATE public.items SET units_per_pack = 4.5 WHERE category = 'jimmys' AND name = 'SAC POPCORN SUCRE CLASSIC SWEET JIMMY''S (POPCORN ZOET)';
UPDATE public.items SET units_per_pack = 3.5 WHERE category = 'jimmys' AND name = 'POPCORN ZOET/ZOUT';

-- Conway dranken (TRAY = 24 stuks, tenzij anders vermeld)
UPDATE public.items SET units_per_pack = 24 WHERE category = 'conway' AND unit = 'TRAY';

-- Conway chips/snoep/choco/ijs (per-product doos-grootte)
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'DORITOS BITS TWIST.H.BBQ 30G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'DORITOS BITS SWEET PAPR.33G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 10  WHERE category = 'conway_snacks' AND name = 'DORITOS WHOPPER TORITILLA 170G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'CROKY CHIPS NATUREL 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'CROKY CHIPS PAPRIKA 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'CROKY CHIPS BOLOGNESE 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'CROKY CHIPS PICKLES 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'CROKY CHIPS BICKY 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'CROKY CHIPS KETCHUP 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY EXPLOS. THAI CURRY 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY EXPLOS. PIZZA PEPP. 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY EXPLOS. SWEET CHILI 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY EXPLOS. SALT & PEPER 150G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'CROKY RINGS PAPRIKA 75G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'CROKY RINGS BOLOGNESE 75G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'CROKY RINGS BBQ 75G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY RIBBLE ROCK PAPR. 130G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY ROLLERS SMOKEY BBQ 100G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 12  WHERE category = 'conway_snacks' AND name = 'CROKY TUBES NACHO CHEESE 100G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 12  WHERE category = 'conway_snacks' AND name = 'CROKY TUBES SWEET CHILI 100G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY PATATAS FR. KETCHUP 100G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 9   WHERE category = 'conway_snacks' AND name = 'CROKY PATATAS FR. PICKLES 100G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 10  WHERE category = 'conway_snacks' AND name = 'CROKY TORTILLA BOLOGNESE 160G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 10  WHERE category = 'conway_snacks' AND name = 'CROKY TORTILLA NACHO CHEESE 160G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 10  WHERE category = 'conway_snacks' AND name = 'CROKY TORTILLA PAPRIKA 160G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 25  WHERE category = 'conway_snacks' AND name = 'LORENZ MONSTER MUNCH ORIG. 75G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'BOUNTY TRIO 85G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'M&M''S CHOCO TREATBAG 90G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'M&M''S CHOCO POUCH 200G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 11  WHERE category = 'conway_snacks' AND name = 'M&M''S MINI CHOCOLADE 176G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 16  WHERE category = 'conway_snacks' AND name = 'M&M CRISPY 77G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 27  WHERE category = 'conway_snacks' AND name = 'M&M''S CRISPY POUCH 170G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 18  WHERE category = 'conway_snacks' AND name = 'M&M''S CRISPY POUCH 374G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'M&M''S CRISPY POUCH 187G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 16  WHERE category = 'conway_snacks' AND name = 'M&M''S PEANUTS 82G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'M&M''S PEANUTS POUCH 200G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 27  WHERE category = 'conway_snacks' AND name = 'M&M BROWNIE 176G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'M&M''S COUCKIE DOUCH 176G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'MALTESERS 68G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 22  WHERE category = 'conway_snacks' AND name = 'MALTESERS 102GR' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MALTESERS POUCH 175G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'MARS 2PACK 70G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'SNICKERS BIG 2PACK 80GR' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'TWIX XTRA 75G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'TWIX WHITE XTRA 75G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'KINDER BUENO 43G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 30  WHERE category = 'conway_snacks' AND name = 'KINDER BUENO WHITE 39G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 8   WHERE category = 'conway_snacks' AND name = 'BELGIANS SUIKERSPIN STRAWB. 35G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 8   WHERE category = 'conway_snacks' AND name = 'BELGIANS SUIKERSPIN FRAMB. 35G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 8   WHERE category = 'conway_snacks' AND name = 'BELGIANS SUIKERSPIN APPEL 35G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 8   WHERE category = 'conway_snacks' AND name = 'BELGIANS SUIKERSPIN GUM 35G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 8   WHERE category = 'conway_snacks' AND name = 'BELGIANS SUIKERSPIN VIOLET 35G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 8   WHERE category = 'conway_snacks' AND name = 'BELGIANS SUIKERSPIN SNOEPAPP. 35G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 40  WHERE category = 'conway_snacks' AND name = 'MENTOS  FRUIT 37,5G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 40  WHERE category = 'conway_snacks' AND name = 'MENTOS  MINT 37,5G.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 40  WHERE category = 'conway_snacks' AND name = 'MENTOS RAINBOW 37,5G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 21  WHERE category = 'conway_snacks' AND name = 'CRAC A NUT PAPR. NOOTJES 200G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'DUYVIS CRAC A NUT PAPR. 45G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 12  WHERE category = 'conway_snacks' AND name = 'FERRERO NUTELLA & co 52G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 12  WHERE category = 'conway_snacks' AND name = 'B&J.CHOCOL.FUDGE BROWNIE 100ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 12  WHERE category = 'conway_snacks' AND name = 'B&J.COOKIE DOUGH 100ML.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'CALIPPO COLA 105ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'CALIPPO ORANGE 105ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'CORNETTO CLASSICO 125ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'OLA CORNETTO STRACC. 140ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 16  WHERE category = 'conway_snacks' AND name = 'CORNETTO KING CONE 260ML VANILE' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 16  WHERE category = 'conway_snacks' AND name = 'CORNETTO KING CONE 260ML CHOC.' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 28  WHERE category = 'conway_snacks' AND name = 'MAGNUM BOMBONIERA 6 PRAL.72ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM ALMOND 110ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM CLASSIC 110ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM AARDBEI/WHITE 100ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM WHITE 110ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM DOUBLE CHOCOLAT 85ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM IJSSTICK EUPHORIA 90ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM DBL GLD CARM BILL. 85ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 20  WHERE category = 'conway_snacks' AND name = 'MAGNUM UTOPIA 85ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 28  WHERE category = 'conway_snacks' AND name = 'OLA SUPER TWISTER 110ML' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'BOUNTY ICE BAR X-TRA 51,6G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'MARS ICE BAR X-TRA 60G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'SNICKERS ICE BAR X-TRA 66G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'SNICKERS PEANUT BUTTER BAR 53G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'SNICKERS WHITE SINGLE BAR 55G' AND unit = 'DOOS';
UPDATE public.items SET units_per_pack = 24  WHERE category = 'conway_snacks' AND name = 'TWIX ICE CREAM SINGLE BAR 47G' AND unit = 'DOOS';
