delete from public.counts where item_id in (select id from public.items where category in ('gadgets','jimmys','lampen','bonnen','brillen'));
delete from public.items where category in ('gadgets','jimmys','lampen','bonnen','brillen');
insert into public.items (category,name,unit,sort_order) values
('gadgets','HP HERMIONE 25cm','STUKS',1),
('gadgets','HP RON 25cm','STUKS',2),
('gadgets','GABYS DOLLHOUSE 18CM KNUFFELS','STUKS',3),
('gadgets','GABYS DOLLHOUSE 20CM SQUIQHY','STUKS',4),
('gadgets','GABYS DOLLHOUSE MAGIQUE HUIS 36CM','STUKS',5),
('gadgets','ZOOTROPOLIS CARROT CONTAINER','STUKS',6),
('gadgets','ZOOTROPOLIS TIN HOLDER GARY','STUKS',7),
('gadgets','ZOOTROPOLIS CUB MINIATURE DOME','STUKS',8),
('gadgets','ZOOTROPOLIS TIN TUB GREEN','STUKS',9),
('gadgets','ZOOTROPOLIS TIN TUB BLUE CINEMA SEATS','STUKS',10),
('gadgets','AVATAR 3 BUCKET PINK','STUKS',11),
('gadgets','AVATAR 3 BUCKET WITH BANSHEE','STUKS',12),
('gadgets','AVATAR 3 DOUBLE WALL CUP','STUKS',13),
('gadgets','AVATAR 3 CONTAINER BANSHEE','STUKS',14),
('gadgets','SPONGEBOB KNUFFELS','STUKS',15),
('gadgets','SPONGEBOB SPEELGOED','STUKS',16),
('gadgets','FIVE NIGHT AT FREDDY''S BUCKET','STUKS',17),
('gadgets','MARIO 30CM','STUKS',18),
('gadgets','LUIGI 30CM','STUKS',19),
('gadgets','YOSHI 30CM','STUKS',20),
('gadgets','MARIO 20CM','STUKS',21),
('gadgets','LUIGI 20CM','STUKS',22),
('gadgets','YOSHI 50CM','STUKS',23),
('gadgets','MARIO POPCORN TIN','STUKS',24),
('gadgets','MARIO POPCORN TIN VIERKANT','STUKS',25),
('gadgets','YOSHI POPCORN BUCKET MET EI','STUKS',26),
('gadgets','LUMA POPCORN BUCKET','STUKS',27),
('gadgets','LUMA PLUSHIE KEYCHAIN','STUKS',28),
('gadgets','HOPPERS/JUMPERS BUCKET','STUKS',29),
('gadgets','PATHE MUG EMILE','STUKS',30),
('gadgets','PATHE MUG CHARLES','STUKS',31),
('gadgets','PATHE KOUSEN EMILE','STUKS',32),
('gadgets','PATHE KOUSEN CHARLES','STUKS',33),
('gadgets','MICHAEL JACKSON TIN TUB','STUKS',34),
('gadgets','MICHAEL JACKSON HAT','STUKS',35),
('gadgets','MICHAEL JACKSON CUP MICRO','STUKS',36),
('gadgets','DEVILS WEARS PRADA SLEUTELHANGERS','STUKS',37),
('gadgets','TOY STORY WOODY+BULLSEYE 25CM','STUKS',38),
('gadgets','TOY STORY 2 ASS. 25CM','STUKS',39),
('gadgets','BUZZ FIGURE 4','STUKS',40),
('gadgets','WOODY FIGURE 4','STUKS',41),
('gadgets','TOY STORY 5 EMMERS','STUKS',42),
('gadgets','MINIONS KNUFFELS','STUKS',43),
('gadgets','MINIONS BUCKETS EMBOSSED','STUKS',44),
('gadgets','MINIONS BEKERS','STUKS',45),
('gadgets','MINIONS JAMES 1920''S HOLLYWOOD SIPPER','STUKS',46),
('gadgets','DIGITAL CIRCUS BEKERS','STUKS',47),
('gadgets','DIGITAL CIRCUS EMMERS','STUKS',48),
('gadgets','STAR WARS MANDALORIAN & GROGU BUCKET','STUKS',49),
('gadgets','STAR WARS MANDALORIAN WITH FIGURE GROGU','STUKS',50),
('gadgets','STAR WARS ATAT CONTAINER','STUKS',51),
('gadgets','TOP GUN HELMET','STUKS',52),
('gadgets','PAW PATROL KUSSENS','STUKS',53),
('gadgets','PAW PATROL POPCORN BUCKET','STUKS',54),
('gadgets','SPIDER-MAN HEAD CONTAINER','STUKS',55),
('gadgets','SPIDER-MAN POPCORN BUCKET VIERKANT','STUKS',56),
('gadgets','SPIDER-MAN POPCORN BUCKET ROND','STUKS',57),
('jimmys','SUPREME CHEESE SAUS 90GR','DOOS',1),
('jimmys','SUPREME NACHOS BARBECUE 140GR','DOOS',2),
('jimmys','SUPREME NACHO SALTED 140GR','DOOS',3),
('jimmys','SUPREME SALSA SAUS 90GR','DOOS',4),
('jimmys','SUPREME FIESTOS 40G','DOOS',5),
('jimmys','RAVIER NACHOS FOLDING TRAY REGULAR','DOOS',6),
('jimmys','PATHE BE GOBELET SUCRE 125CL (POPCORN DOOS ZOET)','DOOS',7),
('jimmys','PATHE BE GOBELET SUCRE 250CL (POPCORN DOOS ZOET)','DOOS',8),
('jimmys','PATHE BE GOBELET SUCRE 500CL (POPCORN DOOS ZOET)','DOOS',9),
('jimmys','PATHE BE GOBELET SALE 125CL (POPCORN DOOS ZOUT)','DOOS',10),
('jimmys','PATHE BE GOBELET SALE 250CL (POPCORN DOOS ZOUT)','DOOS',11),
('jimmys','PATHE BE GOBELET SALE 250CL (POPCORN DOOS ZOET/ZOUT MIX)','DOOS',12),
('jimmys','SAC POPCORN AIR POPPED SALTED JIMMY''S (POPCORN ZOUT)','DOOS',13),
('jimmys','SAC POPCORN SUCRE CLASSIC SWEET JIMMY''S (POPCORN ZOET)','DOOS',14),
('jimmys','POPCORN ZOET/ZOUT','DOOS',15),
('lampen','2000W DHP L (long life)','STUKS',1),
('lampen','3000W DHP L (long life)','STUKS',2),
('lampen','4000W DHP L (long life)','STUKS',3),
('lampen','4500W DHP L (long life)','STUKS',4),
('lampen','6500W DHP L (long life)','STUKS',5),
('bonnen','5 beurtenkaart (1000 stuks)','STUKS',1),
('bonnen','Cadeaubonnen (950 stuks)','STUKS',2),
('bonnen','Excusebonnen (236 stuks)','STUKS',3),
('brillen','Oude Stock 3D brillen - Adultes / Volwassenen','STUKS',1),
('brillen','Oude Stock 3D brillen - Kids','STUKS',2),
('brillen','Stock REAL 3D brillen - Adultes / Volwassenen','STUKS',3);